name: TODO
description: Task to be done in this project
title: '[TODO][Module Name] Feature title'
labels: ['type/feature-request']
body:
  - type: markdown
    attributes:
      value: |
        For better global communication, please write in English.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/RocketChat/RC4Community/issues?q=is%3Aissue) first
        to see whether the same feature was requested already.
      options:
        - label: >
            I have searched in the [issues](https://github.com/RocketChat/RC4Community/issues?q=is%3Aissue) and found no
            similar feature requirement.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short of the task to be done....

  - type: textarea
    attributes:
      label: Use case
      description: Objectives of the task to be completed
      placeholder: >
        Explain what are the objectives of this task....

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: |
        - We would be happy to guide you in the contribution process especially if you already have a good understanding of how to implement the fix.
        - RC4Community is a **for the community - by the community** project and we would love to bring new contributors in.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: 'Thanks for completing our form!'
