import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Infotiles from '../components/infotiles';
import Newscarousel from '../components/newscarousel';
import Personacircle from '../components/personalcircle';
import Discourserankedlist from '../components/discourserankedlist';
import Searchbox from '../components/searchbox';
import Growthcounters from '../components/growthcounters';
import {Container, Row, Col } from "react-bootstrap"
import { fetchAPI } from "../lib/api";

export default function Home(props) {


  return (
    <>
    <Container fluid>
      <Row>
        <Col>
    <div className={styles.container}>
      <div className={styles['home-wrapper']}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <h1 className={styles.title}>
          Welcome to our community
        </h1>

        <p className={styles.description}>
          Let's dream, share, and collaborate in shaping the future of the Rocket.Chat ecosystem together
        </p>
        <p className={styles.description}>
          <a>Read the Guides</a>&nbsp;|&nbsp;<a>Read Release Notes</a>
        </p>
        <Searchbox></Searchbox>
        <p className={styles.description}>
        <Growthcounters></Growthcounters>
        </p>
        <Infotiles></Infotiles>
    

        
        <h2 className={styles['featured-content-heading']}>
        Latest Community News
        </h2>
   
      <Newscarousel carousels={props.carousels}></Newscarousel>

      
      <h2 className={styles['featured-content-heading']}>
        Get What You Need...
      </h2>
      <Personacircle personas={props.personas}></Personacircle>
      <h2 className={styles['featured-content-heading']}>
        Community Activity
      </h2>
      <Discourserankedlist topposts={props.topPosts}></Discourserankedlist>
      </div>
      </div>
      </Col>
      </Row>
    </Container>
    </>
  )
  }
  export async function getStaticProps({ params }) {
    const carousels = await fetchAPI("/carousels");
    const personas = await fetchAPI("/personas");
    const guides = await fetchAPI("/guides");
    const releaseNotes = await fetchAPI("/release-notes");
    const topNavItems = await fetchAPI("/top-nav-item");
    const topPosts = await fetchAPI("/discourses");
  
    return {
      props: { carousels, personas, guides, releaseNotes, topNavItems, topPosts },
      // Next.js will attempt to re-generate the page:
      // - When a request comes in
      // - At most once every 1 second
      revalidate: 1,
    };
  }
  

